version: "3.9"
services:
  # Backend e Banco de Dados (PostgreSQL) no mesmo serviço
  backend-db:
    build:
      context: . # O caminho onde está o Dockerfile
      dockerfile: Dockerfile # Dockerfile para o backend e db
    ports:
      - "9301:9301" # Porta do backend
      - "5432:5432" # Porta do PostgreSQL
    environment:
      - DATABASE_URL=postgresql://admin_provac:Provac%402024@localhost:5432/provac_producao
    volumes:
      - ./backend:/usr/src/app # Sincroniza os arquivos do backend
      - postgres_data:/var/lib/postgresql/data # Persistência dos dados do banco
    command: ["sh", "-c", "pg_ctlcluster 15 main start && npm start"] # Comando para rodar o DB e o Backend juntos

  # Frontend
  frontend:
    build:
      context: ./src # Caminho para o diretório do frontend (src)
      dockerfile: Dockerfile # Dockerfile do frontend
    ports:
      - "9220:9220" # Porta do frontend
    volumes:
      - ./src:/usr/share/nginx/html # Sincroniza os arquivos do frontend
    depends_on:
      - backend-db # Garante que o backend e o db estejam prontos antes de rodar o frontend

volumes:
  postgres_data: # Volume para persistência dos dados do banco
