version: "3.9"
services:
  backend:
    build:
      context: ./backend # Diretório do backend
      dockerfile: Dockerfile
    ports:
      - "9310:9310" # Porta exposta do backend
    environment:
      - DATABASE_URL=postgresql://admin_provac:Provac%402024@192.168.0.232:5432/provac_producao
    depends_on:
      - db # O backend depende do banco de dados
    volumes:
      - ./backend:/app # Mapeia o diretório local para o contêiner
    command: ["./wait-for-it.sh", "db:5432", "--", "npm", "start"]

  frontend:
    build:
      context: ./src # Diretório do frontend (src)
      dockerfile: Dockerfile
    ports:
      - "9220:9220" # Porta exposta do frontend (nginx)
    volumes:
      - ./src:/usr/share/nginx/html # Sincroniza o frontend no contêiner
    depends_on:
      - backend # O frontend depende do backend

  db:
    image: postgres:15
    container_name: postgres-db
    environment:
      POSTGRES_USER: admin_provac
      POSTGRES_PASSWORD: Provac@2024
      POSTGRES_DB: provac_producao
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
